### ISSUE TITLE
Standalone BIMsurfer

### ISSUE THREAD

**Issue by biggosh** [opensourceBIM/BIMsurfer-before2019#143]
Hello.

I've tried to run example1 on an external apache server with tomcat on the same server.
I've untar-ed the the tar.gz package of versione 0.0.20, I'm runnign BIMserver 1.4.0-FINAL with tomcat8.

The error is the one in the first attached file.

So I tried to change the last three link to external javascript in order to use the js on the bimserver. This time the login page was loaded without errors, but after login the error in second screenshot is reported.

May you tell me what I'm doing incorrectly?

Thanks
![first](https://cloud.githubusercontent.com/assets/5515203/15339463/cf3e547e-1c84-11e6-8f78-d1afff0da40d.png)
![second](https://cloud.githubusercontent.com/assets/5515203/15339464/cf415dcc-1c84-11e6-9a54-56bec0e2c872.png)

**Comment by rubendel** [comment]
As has been reported several times, new releases of bimsurfer are not compatible with BIMserver 1.4

**Comment by biggosh** [comment]
I read this, but I was not able to find which version of bimsurfer i compatible with bimserver 1.4.
May I upgrade BIMserver with 1.5.3? But in the releases page I read theat the last stable is 1.4.0 and that 1.5 is a pre-release. Which version of BIMsurfer can I use with 1.4? In a previous issue I was not able to find this, only that the last release is not supported (I used 0.0.20 and not master for this reason).

Thanks in advance and thanks for the great job.
Christian F.

**Comment by biggosh** [comment]
0.0.6 is the last tag with all javascript. If I download this release woult it work with bimserver 1.4.0? May you answer before I waste time investigating on?

**Comment by moElwan** [comment]
@biggosh any news here ?
I'm stuck with versions compatibility.
I've tried hopelessly 
{server 1.4 jar + surfer master }
{server 1.3 jar + surfer master }
{server 1.3 jar + surfer 0.0.16 }
and till now I can't find BIMview .jar anywhere to import in server1.3

**Comment by rubendel** [comment]
I'll try and explain in more detail.

To find the versions of BIMvie.ws and BIMsurfer that are compatible with BIMserver 1.4.0-FINAL-2015-11-04, execute the following steps.
1. Download the JAR or WAR from https://github.com/opensourceBIM/BIMserver/releases/tag/1.4.0-FINAL-2015-11-04
2. Extract the JAR or WAR
3. Navigate to the plugins directory (WEB-INF/plugins when using the WAR)
4. Locate the bimviews-2015-11-04.jar, this version is compatible with BIMserver 1.4.0-FINAL-2015-11-04
5. Extract bimviews-2015-11-04.jar
6. Navigate to js/bimsurfer
7. This version of BIMsurfer is compatible with BIMserver 1.4.0-FINAL-2015-11-04

**Comment by biggosh** [comment]
Thank you for the explenation. 

I'll try this.

**Comment by mahmouds12** [comment]
I tried your solution but still I got errors:

http://127.0.0.1:8082/js/bimserverapi.js?_=1476374005281 Failed to load resource: the server responded with a status of 404 (Not Found)

bimserverapibootstrap.js:27 error Could not connect

bimserverapibootstrap.js:35 Uncaught TypeError: errorCallback is not a function
